basePath: /
definitions:
  models.CombinedData:
    properties:
      api_humidity:
        type: number
      api_temp:
        type: number
      created_at:
        type: string
      diff_hum:
        type: number
      diff_temp:
        type: number
      hum_in:
        type: number
      hum_out:
        type: number
      id:
        type: integer
      lat:
        type: number
      lon:
        type: number
      rainfall:
        type: number
      temp_in:
        type: number
      temp_out:
        type: number
      test_id:
        type: integer
      timestamp:
        type: string
    type: object
  models.TMD:
    properties:
      humidity:
        type: number
      id:
        type: integer
      rainfall:
        type: number
      temperature:
        type: number
      timestamp:
        type: string
    type: object
  models.TimeToDry:
    properties:
      diff_hum:
        type: number
      diff_temp:
        type: number
      hum_in:
        type: number
      hum_out:
        type: number
      id:
        type: integer
      lat:
        type: number
      light:
        type: number
      lon:
        type: number
      temp_in:
        type: number
      temp_out:
        type: number
      test_id:
        type: integer
      timestamp:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the backend API for the Time to Dry project.
  title: Time To Dry API
  version: "1.0"
paths:
  /api/combined:
    get:
      description: Returns all Weather API from tmd table.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CombinedData'
            type: array
      summary: Get all combined records
      tags:
      - CombinedData
  /api/combined/populate:
    post:
      consumes:
      - application/json
      description: Matches closest timestamp from tmd for each time_to_dry record
        and inserts combined row if not duplicate.
      produces:
      - text/plain
      responses:
        "200":
          description: Combined data populated
          schema:
            type: string
      summary: Populate combined_data from time_to_dry and tmd
      tags:
      - CombinedData
  /api/forecast/rain:
    get:
      description: Uses current weather data to estimate rainfall based on weather
        description.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Estimate if it's currently raining or likely to rain
      tags:
      - Forecast
  /api/timetodry:
    get:
      description: Returns all sensor records from the time_to_dry table.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.TimeToDry'
            type: array
      summary: Get all time_to_dry records
      tags:
      - TimeToDry
  /api/tmd:
    get:
      description: Returns all Weather API from tmd table.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.TMD'
            type: array
      summary: Get all tmd records
      tags:
      - TMD
  /api/tmd/recent:
    get:
      description: Returns the 8 most recent weather data records from the TMD table
        within the last 24 hours.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.TMD'
            type: array
      summary: Get last 24 hours of TMD data (latest 8 rows)
      tags:
      - TMD
  /api/tmd/today:
    get:
      description: Returns all weather data from the TMD table for today.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.TMD'
            type: array
      summary: Get today's TMD records
      tags:
      - TMD
  /api/ttd/latest:
    get:
      description: Returns the highest test_id from time_to_dry table. ex.GET http://localhost:8080/api/ttd/status/check?test_id=5
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
      summary: Get the latest test_id
      tags:
      - Test
  /api/ttd/latest/all:
    get:
      description: Returns all time_to_dry rows that share the latest test_id.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.TimeToDry'
            type: array
      summary: Get all rows of latest test_id
      tags:
      - Test
  /api/ttd/latest/last:
    get:
      description: Returns the latest time_to_dry row (by timestamp) for the latest
        test_id.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TimeToDry'
      summary: Get the most recent row of latest test_id
      tags:
      - Test
  /api/ttd/status:
    get:
      description: Returns whether the device is active (sending data within last
        5 minutes).
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Check device status
      tags:
      - Device
  /api/ttd/status/check:
    get:
      description: Returns whether a given test_id is still collecting data or completed.
      parameters:
      - description: Test ID to check
        in: query
        name: test_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Missing or invalid test_id
          schema:
            type: string
        "404":
          description: No records found
          schema:
            type: string
      summary: Check specific test status
      tags:
      - Test
swagger: "2.0"
