import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { GetServerSideProps } from 'next'

type Props = {
  status: string;
  username: string;
}

// Add type annotation to getServerSideProps
export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const { status } = await fetch("http://localhost:8000/status").then(x => x.json());
  const { username } = await fetch("http://localhost:8000/username").then(x => x.json());

  return {
    props: {
      status,
      username,
    },
  };
}

// Destructure with typed props
export default function Home({ status, username }: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>Status is: {status}, your username is: {username}</div>
      </main>
    </div>
  );
}
